#!/usr/bin/env python3
# ruff: noqa: E501 - prose fields remain one literal each for diffable catalog rows.
"""Machine-readable API contract catalog for exact Nuve Samo firmware 1.5.8.

The catalog contains no captured identifiers, payloads, credentials, or vendor
responses.  Route literals retain the firmware's inconsistent leading slash and
Qt ``%0``/``%1`` placeholders so they can be compared directly with the binary.
"""

from __future__ import annotations

from dataclasses import dataclass

APP_SHA256 = "2117a5456445fe57a851ecf09aa452a8d3a2a59d166d4c6f5475bb69d5151c8e"


@dataclass(frozen=True, slots=True)
class ApiContract:
    """One direct route and its application-side contract."""

    literal: str
    methods: tuple[str, ...]
    owners: tuple[str, ...]
    authenticated: bool
    timeout_ms: int
    request_schema: str
    response_and_retry: str
    persistence_hardware_privacy: str
    local_disposition: str
    detail_doc: str


API_CONTRACTS = (
    ApiContract(
        "%0api/device/recovery-image?sn=%1",
        ("POST",),
        (
            "RecoveryUpdater::reportRecoveryInfomation / Sync::sendRecoveryInfomationToServer @ 0x1f5280",
        ),
        True,
        20_000,
        "Raw compact JSON object, or unchanged nonempty /mnt/recovery/filesInfo.json bytes.",
        "Transport result only; returns original bytes. Failure retries every 10 s without a cap only when currently online; an offline failure stalls retained bytes.",
        "Reads recovery cache and may disclose recovery filenames, sizes, and checksums; it does not write boot/root partitions.",
        "unsupported: private recovery inventory and unbounded report retry",
        "messages-reset-api.md",
    ),
    ApiContract(
        "/api/customer",
        ("GET",),
        ("NUVE::Sync::getCustomerInformationManual @ 0x1fc178",),
        True,
        20_000,
        "prepareUrlWithEmail appends a percent-encoded email query.",
        "Network success accepts an empty object as a new customer; nonempty data reads full_name, phone, email, membership, and is_enabled. QML retries retryable failures every 5 s without a cap.",
        "Private contact lookup; accepted name/phone are persisted and a returned-email mismatch is only logged.",
        "unsupported: private customer lookup and onboarding mutation",
        "installer-private-api.md",
    ),
    ApiContract(
        "/api/device/settings",
        ("POST",),
        ("NUVE::Sync::pushDeviceSettingsToServer @ 0x206044",),
        True,
        20_000,
        "Complete device-preference subsection plus serial; exact fields are the full-upload settings object and sibling backlight projection.",
        "DevApi data.setting.last_update acknowledgement; it is delivery/revision evidence, never proof the thermostat later applied desired state.",
        "Captures display/preferences into the private HA Store; no direct relay or equipment action.",
        "supported: validated complete observational preference ingestion",
        "firmware-evidence.md",
    ),
    ApiContract(
        "/api/device/system",
        ("POST",),
        ("NUVE::Sync::pushSystemSettingsToServer @ 0x2066cc",),
        True,
        20_000,
        "Complete 36-field system object including nested serial, topology, timing, lockout, accessory, Wi-Fi name, and strength fields.",
        "Validated 2xx acknowledgement; partial or mismatched-serial objects are rejected locally.",
        "Persists private HVAC/installer baseline and SSID; route is observational and cannot change relays.",
        "supported: strict complete read-only equipment-baseline ingestion",
        "field-matrix.md",
    ),
    ApiContract(
        "/api/sync/schedules2?sn=%0",
        ("GET",),
        ("NUVE::Sync::fetchScheduleV2 @ 0x1fa17c",),
        True,
        20_000,
        "No body; serial is in the query.",
        "Any nonempty success object coerces data with toArray, so missing/wrong-type data clears V2 schedules. QML fetch retry is 5 s and uncapped.",
        "Reconciles persisted schedules and can change effective HVAC targets; no revision or conflict token.",
        "unsupported: destructive coercion and unresolved schedule reconciliation",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "/api/sync/updateAddress",
        ("POST",),
        ("NUVE::Sync::updateAddressInformationManual @ 0x1f9344",),
        True,
        20_000,
        "{zip_code,country,sn} plus optional address1/address2 in external-service mode.",
        "Returns success, error text, and retry classification; QML retries retryable failures every 5 s without a cap.",
        "Persists private address/onboarding state and can participate in timezone setup.",
        "unsupported: private address mutation",
        "installer-private-api.md",
    ),
    ApiContract(
        "/api/technicians/device/install",
        ("POST",),
        ("NUVE::Sync::installDevice @ 0x204638",),
        True,
        40_000,
        "{client:{email,[full_name],[phone]},devices:[{address and equipment fields}],job_id?}.",
        "Any network-error-free reply succeeds regardless of JSON or is_enabled; retryable failures repeat every 5 s without a cap.",
        "Persists private installation identity, advances onboarding, starts housekeeping, and requests full monitor state.",
        "unsupported: fabricated success would activate onboarding transitions",
        "installer-private-api.md",
    ),
    ApiContract(
        "/api/technicians/service-titan/customer/%0?sn=%1",
        ("GET",),
        ("NUVE::Sync::getJobIdInformation @ 0x1fba04",),
        True,
        20_000,
        "Job identifier and serial in path/query; no body.",
        "Any nonempty object can succeed even with network error; accepts identity/address/system_age fields. Retryable failures repeat every 5 s without a cap.",
        "Private job/customer data are persisted and may seed installation settings.",
        "unsupported: private lookup with permissive error handling",
        "installer-private-api.md",
    ),
    ApiContract(
        "/api/technicians/warranty",
        ("POST",),
        ("NUVE::Sync::warrantyReplacement @ 0x2148a8",),
        True,
        20_000,
        "{old_sn,new_sn}; both normally match NN-NNN-NNNNNN and must differ.",
        "Network success reads only optional message; error 299 is nonretryable and other retryable failures use an uncapped 5 s timer.",
        "Old serial is written to QSettings before delivery with no failure rollback; success restarts identity/onboarding.",
        "unsupported: pre-response identity mutation and vendor transaction",
        "installer-private-api.md",
    ),
    ApiContract(
        "/api/zipCode?code=%0",
        ("GET",),
        ("NUVE::Sync::getAddressInformationManual @ 0x1fd72c",),
        True,
        20_000,
        "Uppercased ZIP/postal code in query; no body.",
        "Reads code, nested city/state names and IDs, and optional time_zone_id; mismatch is warned but accepted. Retryable failures repeat every 5 s.",
        "Persists location and can immediately change system/application timezone during setup.",
        "unsupported: private lookup with local timezone side effect",
        "installer-private-api.md",
    ),
    ApiContract(
        "api/designTemperature?sn=%0",
        ("GET",),
        ("NUVE::Sync::getDesignTemperatures @ 0x1fe940",),
        True,
        20_000,
        "No body; serial in query.",
        "DevApi data may contain Fahrenheit heating_temp and cooling_temp; empty data is a proven non-applying no-op.",
        "Values can affect compressor/AUX lockout calculations; the local response supplies no values.",
        "supported: fixed validated empty-data no-op only",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/device/current-sensors?sn=%0",
        ("POST",),
        ("NUVE::Sync::pushSensorValues @ 0x202db4",),
        True,
        20_000,
        "{current_temp,current_humidity,co2_id}; temperature/humidity may be number or string and co2_id is integer category 1..3.",
        "Acknowledgement fields use firmware-specific string coercion; local validation treats the upload as observation, not command confirmation.",
        "Updates runtime room observations only; co2_id is neutral IAQ category, not CO/CO2 ppm.",
        "supported: strict observational ingestion",
        "field-matrix.md",
    ),
    ApiContract(
        "api/device/current-stages?sn=%0",
        ("POST",),
        ("NUVE::Sync::pushCurrentFanState @ 0x202430",),
        True,
        20_000,
        "Numeric fan, heating-stage, and cooling-stage fields (fan 0..1, heat 0..3, cool 0..2).",
        "Validated 2xx acknowledgement; it cannot confirm physical contacts or airflow.",
        "Updates runtime output observations only and never drives hardware.",
        "supported: strict observational ingestion",
        "field-matrix.md",
    ),
    ApiContract(
        "api/device/wifi-off?sn=%0",
        ("POST",),
        ("NUVE::Sync::setWiFiOff @ 0x215818",),
        True,
        20_000,
        "{manual_off:boolean}; optional caller flag enters a nested event loop until reply completion.",
        "Callback ignores body and status; there is no acknowledgement schema or retry contract.",
        "Reports the preference only; it does not enable or disable the Wi-Fi radio.",
        "supported: bounded report-only acknowledgement with no radio action",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/monitor/data?sn=%0",
        ("POST",),
        ("LiveDataManager::endpointUrl @ 0x2aa0ac",),
        True,
        20_000,
        "Raw application/x-protobuf LiveDataPointList; serial in query.",
        "Validated 2xx drains the matching file-backed queue item; sparse fields never mean zero and periodic full-sync records are authoritative.",
        "Observes temperatures, humidity, pressure, IAQ category, stages, mode, topology, Auto bounds, and schedule type; no hardware write.",
        "supported: telemetry with strict schema and range checks",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/monitor/event?sn=%0",
        ("POST",),
        ("EventDataManager::endpointUrl @ 0x2a472c",),
        True,
        20_000,
        "Raw application/x-protobuf EventList with timestamp, name, and optional target.",
        "Validated 2xx drains the corresponding file-backed event queue item.",
        "Privacy-sensitive UI activity is validated then discarded: no logs, persistence, diagnostics, or entity.",
        "supported: privacy-preserving acknowledgement and discard",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/monitor/report?sn=%0",
        ("POST",),
        ("NUVE::Sync::reportCommandResponse @ 0x207d50",),
        True,
        20_000,
        "{data:<command result>}; command text is local retry/log context and absent from the body.",
        "Transport success accepts any parsed object. System callers retry failures after 60 s with counter 2, for at most three attempts.",
        "Can acknowledge only a previously allowlisted monitor command; it cannot authorize arbitrary commands.",
        "supported: bounded command-report acknowledgement inside command recovery",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/sync/alerts",
        ("POST",),
        ("NUVE::Sync::pushAlertToServer @ 0x206d54",),
        True,
        20_000,
        "{alerts:[{type:<mapped string>}],sn}; callback UUID is not transmitted.",
        "Transport success accepts any object and consumes optional alert_id; failure retains queue and retries every 6 s without a cap.",
        "Uploads device Alert/SystemAlert content to a private sink and persists assigned IDs.",
        "unsupported: private alert disclosure and unknown retention",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/sync/autoMode?sn=%0",
        ("GET", "POST"),
        (
            "NUVE::Sync::fetchAutoModeSetings @ 0x1fa92c",
            "NUVE::Sync::pushAutoSettingsToServer @ 0x2057b4",
        ),
        True,
        20_000,
        "GET has no body; POST carries low/high Auto bounds, mode/activity state, and serial-derived identity fields.",
        "GET consumes validated low/high state; POST acknowledgement carries data.last_update. Desired-state success requires a newer authoritative monitor record.",
        "Persists Auto baseline and can change HVAC targets only through fail-closed whole-family control.",
        "supported: canonical read plus guarded reversible control",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/sync/clearSchedule2",
        ("POST",),
        ("NUVE::Sync::clearSchedule @ 0x1ff694",),
        True,
        20_000,
        "Query adds sn and id; no body.",
        "Success when errors is absent/coerces to an empty array; the 3 s QML retry omits the version, so Qt supplies CVersion1=1 and targets the legacy route instead of V2=2.",
        "Deletes persisted V2 schedule state and can change effective targets.",
        "unsupported: destructive schedule mutation and confirmed wrong-route retry defect",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/clearSchedules",
        ("POST",),
        ("NUVE::Sync::clearSchedule @ 0x1ff694",),
        True,
        20_000,
        "Query adds sn and scheduleId; no body.",
        "Uses the permissive generic delete completion; QML queue timing is not a delivery-safe transaction.",
        "Deletes persisted legacy schedule state and can change effective targets.",
        "unsupported: destructive schedule mutation without revision/idempotency",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/client?sn=%0",
        ("GET",),
        ("NUVE::Sync::fetchUserData @ 0x1f9de4",),
        True,
        20_000,
        "No body; serial in query.",
        "Empty object emits no data; nonempty object reads exact string fields email and con-name, coercing missing/wrong types to empty strings.",
        "Persists private account email/name and renders email on the Mobile App page.",
        "unsupported: private account-linkage state",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/sync/forget?sn=%1",
        ("POST",),
        ("NUVE::Sync::resetFactory @ 0x1ffe1c",),
        True,
        20_000,
        "{sn:<serial>}; missing serial returns local success without a request.",
        "NoError is success; Qt error 5 returns true plus a timeout message that prevents the QML reset countdown; other errors fail.",
        "Server deregistration precedes separate destructive config deletion, timezone reset, native forget, and reboot paths.",
        "unsupported: destructive registration/reset workflow",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/sync/getContractorInfo?sn=%0",
        ("GET",),
        ("NUVE::Sync::fetchContractorInfo @ 0x1f96a4",),
        True,
        20_000,
        "No body; serial in query.",
        "Validated metadata response supplies contractor brand/phone and an optional logo URL; stock logo download does not forward bearer auth.",
        "Persists private presentation metadata; local logo URL is purpose-signed, serial/token-bound, PNG-only, and size/dimension bounded.",
        "supported: constrained configured metadata and signed logo projection",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/sync/getSettings?sn=%0",
        ("GET",),
        ("NUVE::Sync::fetchSettings @ 0x1fa54c",),
        True,
        20_000,
        "No body; serial in query. Response is DevApi data containing flat desired HVAC state plus nested singular setting metadata.",
        "Requires complete captured baselines and strictly increasing setting.last_update; bounded polling/backoff preserves unsupported schedule/lock fields with non-applying sentinels/omission.",
        "Can persist preferences and change desired HVAC state; all writes fail closed and require post-delivery authoritative evidence.",
        "supported: canonical baseline response and guarded desired-state control",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/sync/getSn?uid=%0",
        ("GET",),
        ("NUVE::Sync::fetchSerialNumber @ 0x21535c",),
        False,
        20_000,
        "No body; hardware UID in query.",
        "Consumes serial_number string and has_client boolean; missing/mismatch follows alert/test/onboarding branches.",
        "Mutates Sync, DeviceInfo, and two QSettings identity values without request authentication.",
        "unsupported: unauthenticated identity mutation",
        "installer-private-api.md",
    ),
    ApiContract(
        "api/sync/getWirings?uid=%0",
        ("GET",),
        ("NUVE::Sync::fetchWirings @ 0x1f8b70",),
        True,
        20_000,
        "No body; hardware UID in query.",
        "Callback ignores JSON and network status and emits parameterless wiringReady.",
        "May advance installer wiring UI despite no validated wiring state.",
        "unsupported: response-ignoring onboarding transition",
        "installer-private-api.md",
    ),
    ApiContract(
        "api/sync/messages?sn=%0",
        ("GET",),
        ("NUVE::Sync::fetchMessages @ 0x1f9a44",),
        True,
        20_000,
        "No body; serial in query.",
        "Callback discards reply/body/JSON and emits messagesLoaded; actual server messages arrive in full Settings.",
        "A fabricated response cannot safely model rendered/persisted private message state.",
        "unsupported: inert fetch plus private Settings-owned inbox",
        "messages-reset-api.md",
    ),
    ApiContract(
        "api/sync/perftest/result?sn=%0",
        ("POST",),
        ("PerfTestService::sendResultsToServer @ 0x2c3d48",),
        True,
        20_000,
        "Compact {perftest_id,sn,action,result,time,data?}; URL serial is taken from body sn.",
        "A running completion starts hardware even on network failure; failed finished results persist and retry every 300 s; later success can delete an older pending finished result.",
        "Persists private readings and can initiate/revert a 15-minute ordinary HVAC equipment run.",
        "unsupported: direct compressor/heat/fan/accessory activation path",
        "performance-test.md",
    ),
    ApiContract(
        "api/sync/perftest/schedule?sn=%0",
        ("GET",),
        ("PerfTestService::checkTestEligibility @ 0x2c6824",),
        True,
        20_000,
        "No body; serial in query.",
        "Reads integer perftest_id and exact lowercase cooling/heating action; normal eligibility checks use 10:00..11:45 scheduling, jitter, 15-minute failure retry, and 12-hour UI-busy postpone.",
        "A valid response can select a 40 F cooling or 90 F heating target and launch ordinary HVAC control.",
        "unsupported: server-triggered physical equipment test",
        "performance-test.md",
    ),
    ApiContract(
        "api/sync/schedule2/%0?sn=%1",
        ("PUT",),
        ("NUVE::Sync::editSchedule @ 0x1fef80",),
        True,
        20_000,
        "V2 row {is_enable,type,start_time,heat_to,cool_to,fan_on,fan_hours,weekday}; id in path and serial in query.",
        "Any network-success response is accepted and body ignored; exact error Schedule not found. deletes local row. QML edit timer is 4 s.",
        "Mutates persisted schedule and can change effective HVAC target/fan behavior.",
        "unsupported: no revision/idempotency or delivery-safe retry",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/schedule2?sn=%0",
        ("POST",),
        ("NUVE::Sync::addSchedule @ 0x210428",),
        True,
        20_000,
        "V2 row {is_enable,type,start_time,heat_to,cool_to,fan_on,fan_hours,weekday}; serial in query.",
        "Any nonempty success object is accepted; missing id can become undefined. QML add timer is 2 s and delivery ambiguity can duplicate rows.",
        "Adds persisted schedule state that can change effective HVAC target/fan behavior.",
        "unsupported: no revision/idempotency and permissive acknowledgement",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/schedules",
        ("POST",),
        ("NUVE::Sync::addSchedule @ 0x210428",),
        True,
        20_000,
        "Legacy row {is_enable,name,type_id,start_time,end_time,mode_id,humidity,dataSource,weekdays,temp|auto bounds}; native inserts sn.",
        "Any nonempty response object succeeds; QML consumes schedule_id even when absent and queue retry lacks idempotency.",
        "Adds persisted legacy schedule ranges and can change effective HVAC mode/targets.",
        "unsupported: legacy schedule semantics and transactional safety incomplete",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/schedules/%0",
        ("PUT",),
        ("NUVE::Sync::editSchedule @ 0x1fef80",),
        True,
        20_000,
        "Legacy schedule packet; id in path and native inserts sn into body.",
        "Network-success response body is ignored; queued retry has no revision, conflict token, or idempotency key.",
        "Edits persisted legacy schedule ranges and can change effective HVAC mode/targets.",
        "unsupported: legacy reconciliation and delivery ambiguity",
        "scheduling-protocol.md",
    ),
    ApiContract(
        "api/sync/screen-%1?sn=%2",
        ("POST",),
        ("NUVE::Sync::pushLockState @ 0x1fdd80",),
        True,
        20_000,
        "Action substitutes lock or unlock; body is {pin:<exactly four characters>}.",
        "Any response containing locked succeeds after toBool coercion, but QML ignores equality with requested state; failure retries from 1 s exponentially to a 60 s cap without durable journal.",
        "PIN and lock state are saved before delivery and PIN is logged in plaintext; changes local screen lock, not HVAC relays.",
        "unsupported: plaintext secret and unconfirmed precommitted lock mutation",
        "lock-protocol.md",
    ),
    ApiContract(
        "api/sync/update",
        ("POST",),
        ("NUVE::Sync::pushSettingsToServer @ 0x2008a8",),
        True,
        20_000,
        "Complete {sn,temp,humidity,current_humidity,current_temp,co2_id,hold,hold_period,mode_id,fan,backlight,settings,sensors,messages,system,vacation,firmware}.",
        "Acknowledgement is data.setting.last_update; complete upload is durably captured as the canonical device baseline, not treated as application confirmation.",
        "Persists the private whole-device baseline, including topology and unsupported fields; no direct hardware action.",
        "supported: strict complete baseline ingestion",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/weather-current?sn=%0&units=%1",
        ("GET",),
        ("WeatherService::fetchCurrentWeather @ 0x2d0130",),
        True,
        20_000,
        "No body; serial and units in query. Response is OpenWeather-shaped main, weather[0], sys.country, name, and timezone.",
        "Local source must be finite/fresh; missing current temperature returns 503 rather than zero. No automatic unsafe fallback is fabricated.",
        "Outdoor temperature can influence compressor/AUX lockouts; values remain validated runtime input rather than device persistence.",
        "supported: validated fail-closed HA weather projection",
        "firmware-evidence.md",
    ),
    ApiContract(
        "api/weather-forecast?sn=%0&units=%1",
        ("GET",),
        ("WeatherService::fetchForecastWeather @ 0x2cfc2c",),
        True,
        20_000,
        "No body; serial and units in query. DevApi data.list holds up to seven dated rows with dt, temp.day/min/max, optional humidity, and weather[0].",
        "Validated today/future unique rows only; empty list is the sole safe no-forecast response. Refresh is source-event driven plus 45 minutes.",
        "Display/runtime weather input; exact wire swaps forecast high/low display slots to compensate a QML rendering quirk.",
        "supported: validated fail-closed HA forecast projection",
        "firmware-evidence.md",
    ),
)


SUPPORTED_ROUTE_LITERALS = frozenset(
    contract.literal
    for contract in API_CONTRACTS
    if contract.local_disposition.startswith("supported:")
)


def contract_by_literal(literal: str) -> ApiContract:
    """Return exactly one catalog row for a firmware route literal."""

    for contract in API_CONTRACTS:
        if contract.literal == literal:
            return contract
    raise KeyError(literal)
